chore(helm-chart): add support for v1 Ingress to the chart
joeferner/redis-commander pull request #470
Opened 2022-03-15 14:23 UTC by jkirkham-ratehub

- Add a flag `ingress.legacy` to toggle between the deprecated
 Ingress versions and v1.  This defaults to `false` so it will upgrade
 an existing Ingress by default.  Set `ingress.legacy` to `true` if
 the older version of the Ingress are required.  Note this is a
 potential breaking change for some.
 - Split the "standard" and "legacy" ingress templates into separate
 files -- using template conditions to only use one of them.
 - Increment the chart version to 0.2.0.
 - Update the README.md.gotmpl to document the potential breaking
 changes.
 - Regenerate the helm-docs for the new chart version.
 - Add a json schema for the Helm values.yaml -- helm will
 automatically use this to validate values passed to it on install/upgrade.

2022-03-19 22:18 UTC, sseide commented
thanks a lot. and specially for the schema file.

Using the new ingress as default is ok by now - everyone running much older versions should be aware of it and adapt things as needed...

Other things/questions as code remarks above.

2022-03-30 13:42 UTC, jkirkham-ratehub commented
> thanks a lot. and specially for the schema file.
> 
> Using the new ingress as default is ok by now - everyone running much older versions should be aware of it and adapt things as needed...
> 
> Other things/questions as code remarks above.

Any updates on this?  I haven't seen any review comments yet.

2022-03-30 13:53 UTC, sseide commented
> Any updates on this? I haven't seen any review comments yet.

Good question - for me the review comments from myself on your code are visible and pending... They are right below your commit. These are only the first remarks.

Any ideas why you do not see them?

![image](https://user-images.githubusercontent.com/5168949/160850686-4a483a7a-c633-430f-8f8a-1aab98b76f32.png)

2022-03-30 14:04 UTC, jkirkham-ratehub commented
> > Any updates on this? I haven't seen any review comments yet.
> 
> Good question - for me the review comments from myself on your code are visible and pending... They are right below your commit. These are only the first remarks.
> 
> Any ideas why you do not see them?
> 
> ![image](https://user-images.githubusercontent.com/5168949/160850686-4a483a7a-c633-430f-8f8a-1aab98b76f32.png)

Your screenshot says `Pending`.  Perhaps you didn't submit your review?

2022-03-30 19:38 UTC, sseide requested changes

2022-03-30 19:39 UTC, sseide commented
yes - you where right. submit was missing. Sorry for the delay.

2022-03-30 19:43 UTC, sseide commented
i will check it this week when i have some time. Thanks so far!

2022-03-30 21:27 UTC, jkirkham-ratehub commented on k8s/helm-chart/redis-commander/README.md.gotmpl
> -# install helm chart with the custom values
Yeah, done.  Thanks.  Not sure how those got deleted.

2022-03-30 21:29 UTC, jkirkham-ratehub commented on k8s/helm-chart/redis-commander/README.md
> -| image.seccompProfile | string | `"runtime/default"` | Enable SecComp profile when used by cluster, change to "unconfined" to disable -- either AppArmor or SecComp may be enabled by the container ru
I'm using the latest helm-docs v1.7.0 and it does not merge consecutive comment blocks:  that means we only need one line with the `# --` to start a block and consecutive lines up until the setting (key) are used to render the associated comment.

2022-04-02 13:29 UTC, merged

2022-04-02 13:32 UTC, sseide commented
Many thanks - merged code within f9e93edf and updated helm doc validation to use helm-docs 1.7.0 there too.

2022-04-02 13:34 UTC, sseide commented
now i must find time to auto-publish this chart into a helm repo on local github page i think...

2022-04-04 13:12 UTC, jkirkham-ratehub commented
Thanks for the support.  I was glad to help out.